-- MySQL Workbench

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema banco
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `TB_TIPO_PRODUTO`
-- -----------------------------------------------------


CREATE TABLE TB_TIPO_PRODUTO (
  ID_TIPO_PRODUTO INT NOT NULL AUTO_INCREMENT,
  DS_TIPO_PRODUTO VARCHAR(45) NOT NULL,
  PRIMARY KEY (ID_TIPO_PRODUTO))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TB_PRODUTO`
-- -----------------------------------------------------

CREATE TABLE TB_PRODUTO (
  ID_PRODUTO INT UNSIGNED NOT NULL AUTO_INCREMENT,
  ID_TIPO_PRODUTO INT NOT NULL,
  DS_PRODUTO VARCHAR(45) NOT NULL,
  DS_PRECO_PRODUTO DOUBLE NOT NULL DEFAULT 0,
  DT_PRODUTO DATETIME NOT NULL,
  PRIMARY KEY (ID_PRODUTO),
  INDEX fk_TB_PRODUTO_1_idx (ID_TIPO_PRODUTO ASC),
  CONSTRAINT fk_TB_PRODUTO_1
    FOREIGN KEY (ID_TIPO_PRODUTO)
    REFERENCES TB_TIPO_PRODUTO (ID_TIPO_PRODUTO)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TB_CLIENTE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TB_CLIENTE` ;

CREATE TABLE IF NOT EXISTS `TB_CLIENTE` (
  `ID_CLIENTE` INT NOT NULL AUTO_INCREMENT,
  `ID_TIPO_USUARIO` INT NULL,
  PRIMARY KEY (`ID_CLIENTE`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TB_PEDIDO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TB_PEDIDO` ;

CREATE TABLE IF NOT EXISTS `TB_PEDIDO` (
  `ID_PEDIDO` INT NOT NULL AUTO_INCREMENT UNIQUE,
  `ID_USUARIO` INT NULL,
  `ID_CLIENTE` INT NOT NULL,
  PRIMARY KEY (`ID_PEDIDO`),
  INDEX `fk_TB_PEDIDO_TB_CLIENTE1_idx` (`ID_CLIENTE` ASC) ,
  CONSTRAINT `fk_TB_PEDIDO_TB_CLIENTE1`
    FOREIGN KEY (`ID_CLIENTE`)
    REFERENCES `TB_CLIENTE` (`ID_CLIENTE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TB_PAGAMENTO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TB_PAGAMENTO` ;

CREATE TABLE IF NOT EXISTS `TB_PAGAMENTO` (
  `ID_PAGAMENTO` INT NOT NULL AUTO_INCREMENT,
  `ID_PEDIDO` INT NOT NULL,
  `ST_PAGAMENTO` VARCHAR(45) NOT NULL,
  `VL_PAGAMENTO` DOUBLE NOT NULL,
  `DT_PAGAMENTO` DATETIME NOT NULL,
  PRIMARY KEY (`ID_PAGAMENTO`),
  INDEX `fk_TB_PAGAMENTO_1_idx` (`ID_PEDIDO` ASC),
  CONSTRAINT `fk_TB_PAGAMENTO_1`
    FOREIGN KEY (`ID_PEDIDO`)
    REFERENCES `TB_PEDIDO` (`ID_PEDIDO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TB_TIPO_PAGAMENTO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TB_TIPO_PAGAMENTO` ;

CREATE TABLE IF NOT EXISTS `TB_TIPO_PAGAMENTO` (
  `ID_TIPO_PAGAMENTO` INT NOT NULL AUTO_INCREMENT UNIQUE,
  `ID_PAGAMENTO` INT NOT NULL,
  `DS_TIPO_PAGAMENTO` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID_TIPO_PAGAMENTO`),
  INDEX `fk_TB_TIPO_PAGAMENTO_1_idx` (`ID_PAGAMENTO` ASC),
  CONSTRAINT `fk_TB_TIPO_PAGAMENTO_1`
    FOREIGN KEY (`ID_PAGAMENTO`)
    REFERENCES `TB_PAGAMENTO` (`ID_PAGAMENTO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TB_PRECO_PRODUTO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TB_PRECO_PRODUTO` ;

CREATE TABLE IF NOT EXISTS `TB_PRECO_PRODUTO` (
  `ID_PRECO_PRODUTO` VARCHAR(45) NOT NULL,
  `VL_PRODUTO` DOUBLE NOT NULL,
  `DT_INICIO_VIGENCIA` DATETIME NOT NULL,
  `DT_FIM_VIGENCIA` DATETIME NULL,
  `TB_PRODUTO_ID_PRODUTO` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`ID_PRECO_PRODUTO`, `TB_PRODUTO_ID_PRODUTO`),
  INDEX `fk_TB_PRECO_PRODUTO_TB_PRODUTO1_idx` (`TB_PRODUTO_ID_PRODUTO` ASC),
  CONSTRAINT `fk_TB_PRECO_PRODUTO_TB_PRODUTO1`
    FOREIGN KEY (`TB_PRODUTO_ID_PRODUTO`)
    REFERENCES `TB_PRODUTO` (`ID_PRODUTO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TB_ITEM_PEDIDO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TB_ITEM_PEDIDO` ;

CREATE TABLE IF NOT EXISTS `TB_ITEM_PEDIDO` (
  `ID_ITEM_PEDIDO` INT NOT NULL,
  `ID_PRECO_PRODUTO` VARCHAR(45) NOT NULL,
  `ID_PEDIDO` INT NOT NULL,
  PRIMARY KEY (`ID_ITEM_PEDIDO`),
  INDEX `fk_TB_ITEM_PEDIDO_TB_PRECO_PRODUTO1_idx` (`ID_PRECO_PRODUTO` ASC),
  INDEX `fk_TB_ITEM_PEDIDO_TB_PEDIDO1_idx` (`ID_PEDIDO` ASC),
  CONSTRAINT `fk_TB_ITEM_PEDIDO_TB_PRECO_PRODUTO1`
    FOREIGN KEY (`ID_PRECO_PRODUTO`)
    REFERENCES `TB_PRECO_PRODUTO` (`ID_PRECO_PRODUTO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TB_ITEM_PEDIDO_TB_PEDIDO1`
    FOREIGN KEY (`ID_PEDIDO`)
    REFERENCES `TB_PEDIDO` (`ID_PEDIDO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TB_USUARIO`
-- -----------------------------------------------------
-- ------------------------------------
DROP TABLE IF EXISTS `TB_USUARIO` ;

CREATE TABLE IF NOT EXISTS `TB_USUARIO` (
  `ID_USUARIO` INT NOT NULL AUTO_INCREMENT,
  `DS_USUARIO` VARCHAR(45) NOT NULL,
  `DS_EMAIL` VARCHAR(100) NOT NULL UNIQUE,
  `DS_SENHA` VARCHAR(32) NOT NULL,
  `NU_CPF` VARCHAR(11) NOT NULL UNIQUE,
  `NU_TELEFONE` VARCHAR(45) NOT NULL,
  `DS_ENDERECO` VARCHAR(100) NOT NULL,
  `DS_COMPLEMENTO` VARCHAR(50) NULL,
  `ID_CLIENTE` INT NULL,
  PRIMARY KEY (`ID_USUARIO`),
  INDEX `fk_TB_USUARIO_TB_CLIENTE1_idx` (`ID_CLIENTE` ASC),
  CONSTRAINT `fk_TB_USUARIO_TB_CLIENTE1`
    FOREIGN KEY (`ID_CLIENTE`)
    REFERENCES `TB_CLIENTE` (`ID_CLIENTE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


select * from tb_usuario;
